### ISSUE TITLE
[saving] autosave: never + saving on demand

### ISSUE THREAD

**Issue by elandorr** [jacquesh/foo_openlyrics#31] opened 2021-07-16 15:18 UTC
Thanks for this alternative and for making it open source!

But for the love of all that is holy to collectors: Can you please add an option to NEVER autosave? Creating files or editing tags should always be on-demand only. It messes up hashes.

The original component does this perfectly, you can save whenever you want to, but still see the current results.

Thank you!

**Comment by jacquesh** [comment] 2021-07-19 19:49
Duplicate of #18 (see that issue for my justification of why it was done this way).

Also as mentioned in the other thread: I'll consider it. It is not clear to me why you would want to retrieve lyrics and not save them at all (if you don't want to change the files then don't save to tags), the lyrics it retrieves are very likely to be the same next time anyway. If you can provide a reasonable use-case for never saving then that will go some way to make this happen sooner rather than later.

**Closed by jacquesh** 2021-07-19 19:49 UTC
