### ISSUE TITLE
Implement Dark Mode on "Bulk Search For Lyrics" and "Search For Lyrics Manually" windows

### ISSUE THREAD

**Issue by ngs428** [jacquesh/foo_openlyrics#399] opened 2024-09-08 03:27 UTC
These windows do not support Dark Mode.  Can that be changed to support Dark Mode?

Current View:

![Bulk Search](https://github.com/user-attachments/assets/45f369b9-faa4-4880-9946-3bffbeb70ea4)

![Initial Results](https://github.com/user-attachments/assets/1acd4592-7e27-4c93-a31f-4a69f9a7d427)

**Comment by jacquesh** [comment] 2024-09-08 09:39
Duplicate of #302

**Closed by jacquesh** 2024-09-08 09:39 UTC

**Comment by ngs428** [comment] 2024-09-08 11:47
Thanks for the reply on this.  Looks like it is more complicated than it seems.  Unfortunate, but not a huge deal.  Thank you!
