### ISSUE TITLE
Sources not in search list are returning results

### ISSUE THREAD

**Issue by ngs428** [jacquesh/foo_openlyrics#400] opened 2024-09-08 03:35 UTC
Foobar 2.1.5 x64, OpenLyrics 1.11

I only have 4 sources selected in the left column and those 4 should be the only ones used.  When I run a manual search, results from sources in the right show up in the results.  

Sources selected:
![Sources](https://github.com/user-attachments/assets/e0098548-b294-4581-826e-a336e4393d0e)

Results returned (top of list): - Letras and SongLyrics should not be in the results list.  
![Incorrect Sources](https://github.com/user-attachments/assets/821383af-3204-4376-a038-0a67b1ff7b95)

Results returned (bottom of list): Genius and AZLyrics  should not be in the results list.  
![Incorrect Sources 2](https://github.com/user-attachments/assets/db39a840-2b79-4c34-93a0-958fd78f0d3b)

**Comment by jacquesh** [comment] 2024-09-08 09:27
Duplicate of #149 as mentioned above.

**Closed by jacquesh** 2024-09-08 09:27 UTC

**Comment by ngs428** [comment] 2024-09-08 11:36
I see now this was mentioned in #149 and #392.  That is telling that this keeps coming up.  In the other lyric components if a source is on the right side, it is not used.  That is the whole point of moving them between columns.  

I use manual search as my main mode to find lyrics, probably 95% of the time.  Seems like unnecessary searches and results from sources we don’t want searched.  A bit confused on this choice, but I guess there will be no changing it.

**Comment by jacquesh** [comment] 2024-09-08 18:12
For future comments on this issue please use #149 as the main place for discussion around this topic, to make it less likely that things get lost.

Certainly this would be more impactful to add now, given that we just added a bunch more sources and in particular LRCLib which sometimes returns many results.

**Comment by ngs428** [comment] 2024-09-08 20:15
Yes, you read my mind. I was just going to reply a few hours back that the current way of handling sources worked well when there were only a few sources, but it is not feasible in the future as more sources are added.  This will hit the servers will additional, I will call it, unintended queries.  LRCLib I have seen too returns a bunch of results, so the results list is getting very long  and I only care about maybe 2 sources at the moment to get what I need. 

I will summarize my comments on this one into #149.  Just wanted to add this closing comment and I will resume over at #149.  Thanks again!
