### ISSUE TITLE
Auto search can't handle multiple artist vorbis comment

### ISSUE THREAD

**Issue by ChuZhiShen** [jacquesh/foo_openlyrics#45] opened 2021-08-09 13:39 UTC
when the tag(vorbis comment) consist multiple artists, for example : 
title=A Song Title
artist=ArtistOne
artist=ArtistTwo

The automatic lyric searching will fail to retrieve lyric, where manual searching was available to retrieve correct lyric

**Comment by jacquesh** [comment] 2021-08-10 07:01
Dupe of #38. Fixed in the next release.

**Closed by jacquesh** 2021-08-10 07:01 UTC
