### ISSUE TITLE
Correctly read Artist and Track name from streaming radio.

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [jacquesh/foo_openlyrics#60] opened 2021-09-20 13:08 UTC
Thanks for your work on this component.

It doesn't seem to read the Artist and Track name correctly, as LSP does.
Could you please look into supporting this?

TIA :)

**Comment by jacquesh** [comment] 2021-09-20 16:15
Duplicate of #49

**Closed by jacquesh** 2021-09-20 16:15 UTC
