### ISSUE TITLE
Apply offset tag not working

### ISSUE THREAD

**Issue by anazzani** [jacquesh/foo_openlyrics#53] opened 2021-08-27 09:31 UTC
In the editor, Apply offset tag doesn't seem to work (I always get a there is no offset to apply error).

Maybe I'm using the wrong syntax? I'm no .lrc expert.

This is what I tried:

`[offset:-2000]`

or

`[offset:+2000]`

I'm travelling now, so I can't post a complete example, but basically I just edited an existing lrc file adding one the above lines after artist and title.

From #51

**Comment by jacquesh** [comment] 2021-10-05 07:28
Since we don't have any evidence that this is an actual bug (rather than just being malformed tags as above), I'm closing this.
If you have more info or more reproductions of this issue then feel free to re-open

**Closed by jacquesh** 2021-10-05 07:28 UTC
