### ISSUE TITLE
Feature: Separate font config for highlighted lyrics line

### ISSUE THREAD

**Issue by HeresJonny** [jacquesh/foo_openlyrics#88] opened 2021-12-18 20:13 UTC
It would be great if the highlighted line could not only be shown in a different colour but also with a different font, for eample bigger font size and/or bold.

**Comment by jacquesh** [comment] 2022-02-13 22:16
Only just realised this is a dupe of #30. Closing.

**Closed by jacquesh** 2022-02-13 22:16 UTC
Labels: enhancement
