### ISSUE TITLE
Certain lines are automatically removed from local files

### ISSUE THREAD

**Issue by Sevenuno** [jacquesh/foo_openlyrics#74] opened 2021-11-07 00:36 UTC
When I am doing auto search / bulk search, lines start with 1) Lyrics by or 2) Composed by are removed automatically from the local file.

Is it a bug or feature?

**Comment by Sevenuno** [comment] 2021-11-07 01:03
It only happens to certain songs such as this one:

Artist Name : Sia
Track Title : Santa's Coming For Us
Album Title : Everyday Is Christmas (Snowman Deluxe Edition)

Also, the source of lyric was QQ Music.

**Comment by jacquesh** [comment] 2021-11-07 15:41
This is something that some people have asked for, but no, there isn't anything that removes those lines automatically.

Do you have any auto-edits configured to run automatically on downloaded lyrics? Also when you say this happens only in auto/bulk search, does it not happen for manual search? Can you confirm that this also happens after you delete the lyrics you have saved locally?

**Comment by Sevenuno** [comment] 2021-11-07 18:49
I think I know why this happen.

When it auto search or bulk search, it picked lyrics from another edition of the same album [Everyday Is Christmas (Deluxe Edition)].  But, when I search for the lyric manually, only the Snowman Deluxe Edition appears on the list.  The only difference between these two are the two missing lines I am talking about.

Is it normal that manual search and auto search will come up with different results?  If that is the case, please close the issue.

**Comment by jacquesh** [comment] 2021-11-08 20:42
Well the difference is that manual search will give you every option and you select one whereas auto/bulk search has to somehow select one of the available options (usually just...the first one that matches). Depending on your search settings that may go better or worse for some tracks. In particular if you have the "Exclude text in brackets..." setting checked (on the search/root page of the OpenLyrics config) then it will count "My Favourite Song" and "My Favourite Song [Super Radio Cover Smash Hit Version (2021) - Unplugged]" as the same thing (so it might pick the latter even if your tags exactly match the former).

My advice would be to check that box if you *usually* want the extra text excluded and uncheck it if you *usually* don't, and then use manual search to fix up the exceptions.

Closing the issue since this is by design (and simply not what you expected). Please re-open it if you think there is actually a deeper problem here.

**Closed by jacquesh** 2021-11-08 20:42 UTC
Labels: awaiting confirmation
