### ISSUE TITLE
 foo_openlyrics only shows lyrics after manual search

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#99] opened 2022-01-24 16:24 UTC
I have tested it on songs with ID3 Tags LYRICS, UNSYNCEDLYRICS, and .lrc

**Comment by jacquesh** [comment] 2022-01-24 20:39
Can you please give some more info on what you're seeing?

What tags are being searched for? What does the manual search return? What sources do you have enabled? Are there any errors in the console? etc

**Comment by dinfinity** [comment] 2022-02-12 08:06
Same here. No log messages. Right-clicking and pressing 'Search for lyrics' works and shows the lyrics, but when returning to the same song later, no lyrics are loaded.

I think it happens for songs for which the auto-search has failed too many times. I'm guessing the state of the auto-search having failed too many times is (sometimes?) not reset properly if lyrics are found.

**Comment by dinfinity** [comment] 2022-02-12 08:08
This is a duplicate of https://github.com/jacquesh/foo_openlyrics/issues/91 probably.

**Comment by jacquesh** [comment] 2022-02-13 08:09
@dinfinity When you encounter this, does it show the "Auto search skipped..." message? If so then yes I think this is a dupe of #91 (which is now fixed for the next release) and we can close this issue. If not then its probably something else.

**Comment by dinfinity** [comment] 2022-02-13 11:47
@jacquesh: Yes, it does show that message.

**Comment by jacquesh** [comment] 2022-02-13 14:40
Awesome, I'll close this then. If the issue happens again after the next release we can open a new one.

**Closed by jacquesh** 2022-02-13 14:40 UTC
Labels: awaiting confirmation
