### ISSUE TITLE
[Feature Request] karaoke - on the secondary (external) monitor / TV

### ISSUE THREAD

**Issue by s3n0** [jacquesh/foo_openlyrics#243] opened 2023-04-07 09:54 UTC
Hi. 

It would be possible to add or incorporate into this algorithm a secondary output to the second monitor - in fullscreen mode (or in a full window and without frames) - for the purpose of use as a so-called "karaoke" ? 

I want to use it at home, in the family, not for commercial purposes... for reading karaoke, while playing music, on a big TV :). 

I want Foobar2K to play music in the laptop and the lyrics to be displayed / played on the secondary (external) monitor / TV. 

Thanks.

**Comment by jacquesh** [comment] 2023-04-08 21:01
Duplicate of #41

**Closed by jacquesh** 2023-04-08 21:01 UTC

**Comment by Rexadev** [comment] 2023-05-01 18:13
https://github.com/jacquesh/foo_openlyrics/issues/203
