### ISSUE TITLE
Version 10.1 not obeying Searching option for hidden panel

### ISSUE THREAD

**Issue by sveakul** [jacquesh/foo_openlyrics#384] opened 2024-08-31 09:05 UTC
OpenLyrics 1.10.1, Foobar v2.2 x64, Windows 11 x64.

First, congratulations on an exciting new version!

In the "Searching" option there is a checkbox option to automatically search for lyrics even if the OpenLyrics panel is not visible.  But even if that is un-checked, an autosearch is still performed, whether the panel is open or not.  This was not the case in version 1.9, which while not having the new option, would never begin a lyrics search unless its panel was tabbed open.

The downside to having searches performed automatically whether panel is visible or not is that if another lyrics searcher app's panel is open and searching, OpenLyrics behind-the-scenes autosearching will be creating over-activity at the source site that could lead to an IP ban of that user.

**Comment by jacquesh** [comment] 2024-08-31 11:08
Woops, this is definitely not intentional, thanks for reporting!

Can you clarify what you mean by "if the openlyrics panel is not visible"? In particular:
1. Is fb2k minimised?
3. Is there an openlyrics panel on the UI?
4. Is that panel shrunk down to 0 pixels in size/width/height?
5. Are you using the default UI or columns UI?
6. If you're using columns UI, is the panel marked as "hidden"

**Comment by jacquesh** [comment] 2024-09-01 09:04
Hmm, I can't reproduce this. I have the "search while not visible" option disabled, setup a tab panel on the default UI with openlyrics and an album art viewer and if I select the art viewer and start a new track, it doesn't search.

Do you have debug logs for a minimal reproduction of this? There aren't really any useful logs around this bit of logic so I'm not sure what I'd get from them tbh but maybe there's something else going on?

**Closed** 2024-09-02 20:58 UTC
Labels: bug

**Comment by jacquesh** [comment] 2024-09-02 21:02
Ah, I hadn't seen your HA forum link. Inspired by Paaufo's comments and taking a look at the code, I see it was actually just not doing the correct checks when handling track metadata for internet radio. Thanks for the help, the automation is running now so by the time you read this there should be a v1.10.2 release on github that fixes the issue. If you could confirm that'd be helpful and I'll put it up on the fb2k component tracker soon.
