### ISSUE TITLE
Add option to Fullscreen Lyrics

### ISSUE THREAD

**Issue by lkjdsf65** [jacquesh/foo_openlyrics#224] opened 2022-11-12 18:33 UTC
Thank you jacques for your contribution to the Foobar2000 community. Could you add the option to see the lyrics in full screen mode? And it would be very good if you could see the Album cover at the same time

**Comment by jacquesh** [comment] 2022-11-13 11:27
Album art is covered by #80 
Would #41 cover your fullscreen requirement? If we added support for showing lyrics in a separate window (which you could configure to display however you want) then you could just maximise that?

**Comment by Rexadev** [comment] 2023-02-16 09:35
Duplicate of https://github.com/jacquesh/foo_openlyrics/issues/203

**Closed** 2023-02-18 08:16 UTC
