### ISSUE TITLE
Prefer synced lyrics

### ISSUE THREAD

**Issue by Eradev** [jacquesh/foo_openlyrics#101] opened 2022-01-31 20:11 UTC
I'd like to request an additional feature:

Have an option to use synced lyrics (.lrc) if found, over plain text files.

**Comment by jacquesh** [comment] 2022-02-01 12:51
This should happen already. If you have two files with the same name in the same directory that OpenLyrics searches, except one of them is .lrc and the other is .txt, it should always load the lrc. Is that not the case for you? Can you give more details? Are there any warnings/errors in the console?

**Comment by Eradev** [comment] 2022-02-01 14:58
Sorry I wasn't clear enough.

I'm not talking about local files, but from external sources. Sometimes it would get unsynced lyrics but a manual search would reveal a synced one from the same source. There are no errors in the console because I guess it worked.

Ex:
![image](https://user-images.githubusercontent.com/10186499/151992115-1fe1401b-f627-4eb9-84c9-d36468f8423a.png)

First one is unsynced, and the 2nd is a lrc. I want it to return the .lrc if it's found before the .txt one.

**Comment by jacquesh** [comment] 2022-02-01 15:48
Oh I see. The automated search is more strict about what it considers a "matching" result than the manual search is which may be the cause for the difference here.

What are the exact tags on your file? If they match the first one exactly then that would explain it. If the only difference between your tags and the search result you want is inside parentheses (e.g "Deluxe Edition" as seen in your screenshot above) then you can also try the "Exclude text in brackets..." search option.

If the automated search finds 2 results that both match your tags exactly then it should ideally take a synced one over an unsynced one but from your screenshot I doubt that's the case here?

**Comment by Eradev** [comment] 2022-02-15 22:15
I see. My tags are indeed not identical to the results.

Any way to make the automated search less strict?

**Comment by jacquesh** [comment] 2022-02-16 07:47
Apart from the "Exclude text in brackets..." option mentioned above, no. The automated search needs to be fairly strict otherwise it would actually find the wrong lyrics all the time.

If this happens occasionally I would say just use the manual search feature (that's exactly what its for). If it happens all the time...then short of there being an actual bug I can't really help you. Adding more ways to make the auto-search less strict would not actually help I don't think =/

Either way, since it seems the issue is with the available data (either in your tags or on the source) and not with OpenLyrics, I'll close this.

**Closed by jacquesh** 2022-02-16 07:47 UTC
Labels: awaiting confirmation
