### ISSUE TITLE
Lyrics translation and MusixMatch translation support

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#170] opened 2022-08-25 17:23 UTC
> - How you think the new feature/improvement would be helpful, or what problem you think it would solve

Very obvious but,
1. Good for listening to music that the user doesn't speak language of.
2. Help in learning language.

I found these -
https://github.com/Spikatrix/Traly
https://github.com/markzhai/LrcCleaner
https://github.com/brandonw3612/TranslateLrc
https://github.com/slowfog/LrcSpliter

## More people are interested in Translation
https://www.reddit.com/r/foobar2000/comments/y35b04/comment/isba0jm/?context=3

# ESLyric 
ESLyric can get MusixMatch translations ?
"ESLyric supports js syntax lyrics source and can also display translations"

LRC - https://github.com/Robotxm/ESLyric-LyricsSource/
https://github.com/ESLyric/scripts/tree/main/parser

https://www.musixmatch.com/lyrics/Green-Day/Basket-Case/translation/german

# Related
https://github.com/jacquesh/foo_openlyrics/issues/280

**Comment by jacquesh** [comment] 2022-08-25 21:28
Please provide addition information, as mandated in the feature request template. Closing until then.

Is this even something musixmatch provides? Can you link to any documentation on it?

On the balance of it, I probably wouldn't want to add this anyway (at least without many people asking for it) because of the amount of complication it would introduce.

**Comment by Rexadev** [comment] 2022-08-26 07:59
>Is this even something musixmatch provides? Can you link to any documentation on it?

https://www.youtube.com/watch?v=Cdj87UTuKQ8
https://support.musixmatch.com/article/89-how-can-i-display-the-lyrics-translation

> On the balance of it, I probably wouldn't want to add this anyway (at least without many people asking for it) because of the amount of complication it would introduce.

Add option in setting to turn in on/off.

**Comment by jacquesh** [comment] 2022-08-26 16:24
> Add option in setting to turn in on/off.

No. That would be *more* complication.

**Comment by Rexadev** [comment] 2022-08-26 18:14
> > Add option in setting to turn in on/off.
> 
> No. That would be _more_ complication.

I mean on and off option for downloading translations. Not translated lines

**Comment by Rexadev** [comment] 2022-08-30 13:35
@jacquesh Please reopen this

**Comment by Rexadev** [comment] 2022-10-16 04:40
@jacquesh More people are interested in Translation
https://www.reddit.com/r/foobar2000/comments/y35b04/comment/isba0jm/?context=3

**Comment by Rexadev** [comment] 2022-10-18 19:17
@jacquesh would you allow if someone else writes a patch?

**Comment by jacquesh** [comment] 2022-10-19 07:03
Maybe, but realistically, probably not. The problem isn't doing the work to add it, the problem is that I don't think translation really falls into the realm of "things openlyrics should concern itself with" and that once its added I have to maintain it for all time or risk the wrath of users if I take it out later in pursuit of simplicity.

**Comment by Rexadev** [comment] 2023-05-01 08:53
```
#include <curl/curl.h>
#include <libxml/parser.h>
#include <libxml/tree.h>

// Function to retrieve translated synced lyrics from musixmatch.com
std::string getTranslatedLyrics(int trackId, std::string apiKey, std::string lang) {
    // Construct the API URL
    std::string apiUrl = "https://api.musixmatch.com/ws/1.1/track.subtitle.get?"
                         "track_id=" + std::to_string(trackId) + "&"
                         "apikey=" + apiKey + "&"
                         "subtitle_format=mxm&"
                         "language=" + lang;
    
    // Initialize libcurl and set the options
    CURL* curl = curl_easy_init();
    curl_easy_setopt(curl, CURLOPT_URL, apiUrl.c_str());
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, &curlWriteCallback);

    // Create a buffer to hold the response
    std::string responseBuffer;

    // Set the buffer as the data to write to
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &responseBuffer);

    // Send the request
    CURLcode res = curl_easy_perform(curl);

    // Check for errors
    if (res != CURLE_OK) {
        // Handle error
    }

    // Cleanup libcurl
    curl_easy_cleanup(curl);

    // Parse the XML response
    xmlDocPtr doc = xmlReadMemory(responseBuffer.c_str(), responseBuffer.length(), NULL, NULL, 0);
    xmlNodePtr root = xmlDocGetRootElement(doc);

    // Traverse the XML tree to find the synced lyrics
    xmlNodePtr trackNode = root->children;
    while (trackNode != NULL) {
        if (xmlStrcmp(trackNode->name, (const xmlChar*)"track") == 0) {
            xmlNodePtr subtitleNode = trackNode->children;
            while (subtitleNode != NULL) {
                if (xmlStrcmp(subtitleNode->name, (const xmlChar*)"subtitle") == 0) {
                    xmlNodePtr syncedLyricsNode = subtitleNode->children;
                    while (syncedLyricsNode != NULL) {
                        if (xmlStrcmp(syncedLyricsNode->name, (const xmlChar*)"synced_lyrics") == 0) {
                            // Found the synced lyrics
                            std::string syncedLyrics = (char*)xmlNodeListGetString(doc, syncedLyricsNode->xmlChildrenNode, 1);
                            xmlFreeDoc(doc);
                            xmlCleanupParser();
                            return syncedLyrics;
                        }
                        syncedLyricsNode = syncedLyricsNode->next;
                    }
                }
                subtitleNode = subtitleNode->next;
            }
        }
        trackNode = trackNode->next;
    }

    // Cleanup libxml2
    xml

```

**Comment by Rexadev** [comment] 2023-05-01 08:56
```
#include "stdafx.h"
#include "../SDK/foobar2000.h"
#include "../helpers/helpers.h"
#include "../SDK/components.h"
#include <string>
#include <sstream>
#include <algorithm>
#include <curl/curl.h>
#include <rapidjson/document.h>
#include <rapidjson/writer.h>
#include <rapidjson/stringbuffer.h>
#include <map>
#include <regex>

using namespace rapidjson;

class musixmatch_lyrics : public lyrics_provider_v2 {
private:
    std::string useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0";

    std::string get_lyrics_url(const std::string& artist, const std::string& title, const std::string& lang) {
        std::string url = "https://www.musixmatch.com/ws/1.1/macro/search_lyrics?user_language=en&q_lyrics=";
        std::string query = artist + " " + title;

        std::stringstream ss;
        ss << std::hex << std::uppercase << std::hash<std::string>{}(query);

        url += ss.str();
        url += "&q_track=";
        url += url_encode(title);
        url += "&q_artist=";
        url += url_encode(artist);
        url += "&q_lang=";
        url += lang;

        return url;
    }

    std::string get_lyrics(const std::string& url) {
        CURL* curl = curl_easy_init();

        if (!curl) {
            return "";
        }

        curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
        curl_easy_setopt(curl, CURLOPT_USERAGENT, useragent.c_str());
        curl_easy_setopt(curl, CURLOPT_HTTPGET, 1L);

        std::string response;
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_callback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);

        CURLcode res = curl_easy_perform(curl);

        curl_easy_cleanup(curl);

        if (res != CURLE_OK) {
            return "";
        }

        Document doc;
        if (doc.Parse(response.c_str()).HasParseError()) {
            return "";
        }

        const Value& status = doc["message"]["header"]["status_code"];
        if (status.GetInt() != 200) {
            return "";
        }

        const Value& lyrics = doc["message"]["body"]["macro_calls"]["track.lyrics.get"]["message"]["body"]["lyrics"]["lyrics_body"];
        std::string str_lyrics = lyrics.GetString();

        str_lyrics.erase(std::remove(str_lyrics.begin(), str_lyrics.end(), '\r'), str_lyrics.end());
        str_lyrics.erase(std::remove(str_lyrics.begin(), str_lyrics.end(), '\n'), str_lyrics.end());

        return str_lyrics;
    }

    std::string get_translated_lyrics(const std::string& lyrics_id, const std::string& lang) {
        std::string url = "https://www.musixmatch.com/ws/1.1/track.lyrics.translation.get?commontrack_id=";
        url += lyrics_id;
        url += "&selected_language=";
        url += lang;

        CURL* curl = curl_easy_init();

        if (!curl) {
            return "";
        }

        curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
        curl_easy_setopt(curl, CURLOPT_USER

```

**Comment by Rexadev** [comment] 2024-08-11 10:15
@jacquesh reconsider this please

**Comment by Rexadev** [comment] 2024-10-07 08:02
ESLyric can get MusixMatch translations ?
"ESLyric supports js syntax lyrics source and can also display translations"

How to get [enhanced format](https://en.wikipedia.org/wiki/LRC_(file_format)#Enhanced_format)

LRC - https://github.com/Robotxm/ESLyric-LyricsSource/
https://github.com/ESLyric/scripts/tree/main/parser

https://www.musixmatch.com/lyrics/Green-Day/Basket-Case/translation/german

@jacquesh

**Comment by jacquesh** [comment] 2024-11-12 20:34
Out of scope.

**Closed by jacquesh** 2024-11-12 20:34 UTC

**Comment by Rexadev** [comment] 2025-05-25 06:58
@jacquesh Anything changed. Would you consider adding this ?
