### ISSUE TITLE
"Reset Capitalization" in "Auto-edit Lyrics" changes all standalone and contraction "I" to "i"

### ISSUE THREAD

**Issue by ngs428** [jacquesh/foo_openlyrics#277] opened 2023-07-03 19:01 UTC
I am using 1.6.  

When using Reset Capitalization, lyrics such as this:

Because there's no place that **I'd** be without you
We know it's too far to discard the life **I** once knew

Will be set to this:

Because there's no place that **i'd** be without you
We know it's too far to discard the life **i** once knew

The "I", should stay capitalized, along with all its personal pronoun contractions such as I'm, I've, I'll and I'd.

**Comment by jacquesh** [comment] 2023-07-06 21:31
Duplicate of  #83

**Closed by jacquesh** 2023-07-06 21:31 UTC
