### ISSUE TITLE
[Feature Request] Allow manual scrolling if scroll type is automatic.

### ISSUE THREAD

**Issue by vnnegt** [jacquesh/foo_openlyrics#102] opened 2022-02-07 05:52 UTC
For **non-synced** lyrics, sometimes the automatic scrolling is too slow or too fast.

It would be nice to be able to manually scroll to catch up or slow down, and then have it revert back to automatic scrolling when you're not manually scrolling.

This would be similar to how **Lyrics Show Panel v3** works.

Digging the plugin, thanks!

**Comment by jacquesh** [comment] 2022-02-08 09:54
Duplicate of #63

**Closed by jacquesh** 2022-02-08 09:54 UTC
