### ISSUE TITLE
Bug - Crash on Startup - Foobar 2.0 Beta and OpenLyrics 1.5

### ISSUE THREAD

**Issue by Matte0Cal0** [jacquesh/foo_openlyrics#250] opened 2023-04-10 18:24 UTC
#### Steps to reproduce
1. Update to OpenLyrics 1.5 a few days ago
2. Enjoy the new version as it's working perfectly
3. Startup foobar a few days later and it crashes on startup

#### Expected behavior
Foobar Crashes on startup instead of working flawlessly

#### Versions
Foobar 2.0 Beta 31, rolling back to 30 didn't fix the problem
OpenLyrics 1.5

#### Additional information

OpenLyrics 1.5 used to work until I wanted to use Foobar a few days later. Opening Foobar would make it crash to startup less than a second after being opened, and crash logs  would Indicate an Illegal Operation on the Kernel.
[failure_00000026.txt](https://github.com/jacquesh/foo_openlyrics/files/11192829/failure_00000026.txt)

Due to the recent update, I started identifying from the way down as OpenLyrics was my instance's newer possible point of failure. 
I also noticed that an OpenLyrics zip was present in my component-updates. 
This made me want to rewind to 1.4 to see if the problem disappeared, which actually fixed the issue.
Trying to update back to 1.5 through the component menu caused Foobar to crash on startup again unless I deleted the possibly broken zip file.

My instance is now fixed, but I wanted to share my problem with you or others who could meet the same issue.

Matte0Cal0

**Comment by Matte0Cal0** [comment] 2023-04-10 21:24
Exactly, this is on point. I can confirm I was indeed running 1.5 as I had the Editor in dark mode.

I wanted to send the .dmp on the first post but GitHub doesn't allow me to do so. I uploaded it on GDrive as an alternative.
I would suppose the zip got indeed corrupted, as updating the component without deleting such zip beforehand would crash before fb2k could even prompt the option to restart to finish the install.

Here is the link,
https://drive.google.com/file/d/18lqSiCmM-nR_8RRN9u5HT88mhFrDhYyy/view?usp=sharing

Matte0Cal0

**Comment by snowbie** [comment] 2023-04-11 15:49
Deleting the configuration file fixed it for me, but you lose your settings obviously

**Comment by cnieuweboer** [comment] 2023-04-12 08:11
I had a crash on startup too. Deleting the config file fixed it. 
The crashy config file:
[foo_openlyrics.dll.cfg.zip](https://github.com/jacquesh/foo_openlyrics/files/11208815/foo_openlyrics.dll.cfg.zip)

**Comment by snowbie** [comment] 2023-04-12 10:59
May have been fixed in latest beta
https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Version_2.0_Beta_Change_Log

**Comment by Matte0Cal0** [comment] 2023-04-12 11:01
> Resolved a disagreement with foo_openlyrics resulting in startup crashing.

Says it clearly.
From what I could identify from my crashlogs was a misbehaving bugcheck, perhaps a specific handshake between Openlyrics and fb2k wasn't working properly.

**Comment by jacquesh** [comment] 2023-04-12 21:40
Ah. Sorry about this everyone. It is indeed an openlyrics crash caused by the metrics prompt trying to do something it shouldn't have (which, I'll be honest, is disappointing because I did specifically try to prevent that from causing any user-visible errors and it also means that it won't collect any data from the people whose fb2k crashes). 

The reason deleting your config file "fixes" the problem is just that it restarts the 7-day countdown before prompting for metrics. If you're on fb2k v2 then for now I'd suggest either reverting openlyrics to v1.4 or updating for fb2k to the latest version (which, as snowbie pointed out, should have at least prevented the crash, although I've not had a chance to test it myself yet so I can't confirm personally).

While I do specifically try to test new versions before releasing them to you all, this one got through mostly because I'm not yet using the fb2k v2 beta and in v1 it doesn't crash. I'll try to at least give new versions a whirl on a recent v2 beta before release next time! I will put together a v1.6 release by the end of the week (but probably not before the end of Friday, realistically).

**Closed** 2023-04-13 07:06 UTC
Labels: bug

**Comment by jacquesh** [comment] 2023-04-13 07:17
Ok nevermind the weekend, I've just put out v1.6 that contains only this bugfix. Please do tell all your friends to update to v1.6 :)
