### ISSUE TITLE
Background Albumart doesn't work when playing same song again

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#348] opened 2024-03-02 16:55 UTC
https://github.com/jacquesh/foo_openlyrics/assets/62152714/46408fbc-c6f5-45d3-90cd-b5ed7a2534f8

#### Versions

* foobar2000 version: 2.0
* OpenLyrics version: 1.8

#### Debug logs

```
Opening track for playback: "X:\...\Young.opus"
Opening track for playback: "X:\...\Taylor Swift - Mine.mp3"
Opening track for playback: "X:\...\Taylor Swift - Mine.mp3"
Opening track for playback: "X:\...\Taylor Swift - Ours.mp3"
Opening track for playback: "X:\...\Taylor Swift - Ours.mp3"
Opening track for playback: "X:\...\Taylor Swift - Mine.mp3"
```

#### Additional information

**Comment by jacquesh** [comment] 2024-03-02 18:16
Duplicate of #318

**Closed by jacquesh** 2024-03-02 18:16 UTC
