### ISSUE TITLE
Preferences not adjusting to window size

### ISSUE THREAD

**Issue by regorxxx** [jacquesh/foo_openlyrics#259] opened 2023-05-02 16:35 UTC
From here:
https://hydrogenaud.io/index.php/topic,120812.msg1026183.html

#### Steps to reproduce
1. Enable dark mode
2. Open preferences window

![image](https://user-images.githubusercontent.com/83307074/235728643-ad874387-8810-445a-8c8b-791742fefc3b.png)
![image](https://user-images.githubusercontent.com/83307074/235728659-24e8ca06-20f9-4d1b-88f4-9c10e2eba6a7.png)

#### Expected behavior
Content adjusted to window size (width).

#### Versions
* foobar2000 version:  foobar2000 v2.0 32bit 64bit
* OpenLyrics version: OpenLyrics 1.6 (2023-04-12)
* Columns UI, Default UI, 32bit 64bit

**Comment by jacquesh** [comment] 2023-05-02 17:45
This is a duplicate of #228. It isn't specific to Columns UI or Dark Mode, this is an issue with UI Scaling on high-dpi monitors.

I looked into fixing it initially for v1.5 but I struggled to come up with a good solution that worked properly *without* requiring me to manually resize everything. In theory (as far as I know, I've not done it elsewhere before) I should be able to mark the window with the correct DPI-awareness setting and let Windows automatically scale everything. Sadly this doesn't appear to work in the way that I expect =/ If anybody has any bright ideas on how to do this properly without writing code to manually scale everything, that'd be amazing.

Regardless I should put some more time into this anyway. At the very least to write some small experiments to see how the Windows auto-scaling works outside of fb2k, as a baseline for what I should expect.

**Closed by jacquesh** 2023-05-02 17:45 UTC
