### ISSUE TITLE
Add option to get translation for the lyrics

### ISSUE THREAD

**Issue by Arthurfogo7** [jacquesh/foo_openlyrics#199] opened 2022-10-14 23:34 UTC
<!-- Please give a detailed description of the desired improvement here
Be sure to include at least:
- It would help people who don't know the language in which the song is, spotify does something similar but only a few songs have this feature

-Deepl, google translator or bing would work just fine, but I think this feature would improve a lot the experience using this

Thank you in advance

**Comment by jacquesh** [comment] 2022-10-15 08:02
Dupe of #200

**Closed by jacquesh** 2022-10-15 08:02 UTC
