### ISSUE TITLE
Does not auto remove "All Blank lines"

### ISSUE THREAD

**Issue by tortuosit** [jacquesh/foo_openlyrics#209] opened 2022-10-24 11:32 UTC
Hi guys, as reported in https://hydrogenaud.io/index.php/topic,120812.msg1018009.html#msg1018009

I have set it to remove all blank lines in the options. But it does not auto remove them.

#### Steps to reproduce
1. Set options to auto remove all blank lines
2. Try it on a track with " (Artist:"Radiohead", Album: "Kid A Mnesia", Title: "If You Say The Word", Source: Netease)
3. Blank lines still existing

#### Expected behavior
Remove all blank lines

#### Versions
* foobar2000 version: 2 beta 12
* OpenLyrics version: 1.3

**Comment by jacquesh** [comment] 2022-11-17 21:07
I couldn't reproduce this, but I've fixed a potential bug here. Should be fixed for the next release.

If you experience this again, please have openlyrics save to file and upload the exact file that it saved, so I can check against exactly that.

**Closed by jacquesh** 2022-11-17 21:07 UTC
Labels: bug
