### ISSUE TITLE
v2: Not reading lyrics in mp3, opus, m4a works for flac

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#229] opened 2022-12-01 06:33 UTC
### F2K v2Beta14 OpenLyics 1.4
![image](https://user-images.githubusercontent.com/62152714/204981831-6ec7e3e7-2f57-43a2-bc0e-991f65bce610.png)
![image](https://user-images.githubusercontent.com/62152714/204981845-a1fbc2da-0d1f-49f8-90ee-fd90cdd4d183.png)

### F2K v1.6.14 OpenLyics 1.4
![image](https://user-images.githubusercontent.com/62152714/204981860-b0aab57b-0d1c-4a87-bf3a-3c3a3a002be4.png)

It is also tries to update the lyrics to "."
![image](https://user-images.githubusercontent.com/62152714/204999352-2813af64-ccd2-4060-ba64-f30275cdcaeb.png)

#### Steps to reproduce
1.
2.
3.

#### Versions

* foobar2000 version: v2Beta14
* OpenLyrics version: 1.4

#### Additional information
Can't read SYNCEDLYRICS or LYRICS (unsynced)

**Comment by jacquesh** [comment] 2022-12-04 08:03
Pasting the template does not serve any purpose if you don't fill in any details. A sequence of screenshots is not a bug report. Please include a clear & concise description of the problem in future rather than making me trawl through your screenshots to try and figure out on what you're referring to in the title.

This could be an fb2k issue. I don't believe tag-reading code was changed recently in openlyrics. Although the search also provides multiple metadata results, can you confirm that both are invalid in the fb2k-v2-beta case?

What do you mean by "Can't read SYNCEDLYRICS or LYRICS (unsynced)"? Can you provide debug console output showing it trying and failing to read those tags? What if you set one of those as the destination for saving lyrics and then try make an edit, does the console show anything of note in that case?

**Comment by Rexadev** [comment] 2022-12-04 09:13
New observation for some mp3 s it works

> Although the search also provides multiple metadata results, can you confirm that both are invalid in the fb2k-v2-beta case?
![image](https://user-images.githubusercontent.com/62152714/205482881-e42445ce-71f3-44ea-83ba-7f326e497ccb.png)

>What do you mean by "Can't read SYNCEDLYRICS or LYRICS (unsynced)"? 
RE: foo_openlyrics shows . instead of lyrics

>Can you provide debug console output showing it trying and failing to read those tags?
Opening track for playback: "*\Antarctica.m4a"
Opening track for playback: "*\3 Doors Down - Here Without You.mp3"

>What if you set one of those as the destination for saving lyrics and then try make an edit, does the console show anything of note in that case?
Explain

**Comment by jacquesh** [comment] 2022-12-28 15:19
Quite by accident, I managed to reproduce this today while looking into an unrelated issue. I've found the cause and and it should be fixed in the next release :)

**Closed by jacquesh** 2022-12-28 15:19 UTC
Labels: bug
