### ISSUE TITLE
[Feature Request] Download lyrics for all selected in library.

### ISSUE THREAD

**Issue by WSADKeysGaming** [jacquesh/foo_openlyrics#64] opened 2021-09-30 08:01 UTC
LSP3 had a great feature where, if you right clicked on your library with a file or more selected, it would find lyrics for everything selected and add that either via ID3 or .txt next to the file. It would be great to have this feature back as it made adding lyrics to my library of 15,000 songs one click away.

**Comment by jacquesh** [comment] 2021-09-30 12:09
Duplicate of #58

**Closed** 2021-09-30 12:21 UTC
