### ISSUE TITLE
Search and fetch local lyrics (.lrc or .txt files) located in same directory as the audio file

### ISSUE THREAD

**Issue by apprenti-sorcier** [jacquesh/foo_openlyrics#422] opened 2024-11-12 22:00 UTC
My lyrics have the same file name as the audio tracks, obviously with a different extension. But I can’t switch from Lyric Show 3 to OpenLyrics because the latter is unreliable.

When I set it with %filename%, some of the existent lyrics show this instead of the file content. I don’t see any difference to the other files that are shown fine.
![384532299-6f729719-d6ab-4b29-9fd9-3e6ce1032182](https://github.com/user-attachments/assets/437c5a48-fbc3-4277-91ef-001e71f4d56a)
All these files are shown fine by the Lyric Show 3.
I even removed all the possible Internet sources so that there is no Chinese interference, but it’s not that either.
What is the problem ?

#### Steps to reproduce
Put %filename% instead of the default $replace(…) in the settings (Search sources / Local files / File name format)

#### Expected behavior
Considering the original setting working on both kinds of formats (.lrc and .txt), I suppose you don’t have to set an extension (actually if you do, it will only work on that one type of format).

#### Versions
* foobar2000 version: latest 2.1.6
* OpenLyrics version: latest 1.11

#### Debug logs
The console doesn’t show anything else but “Opening track for playback: "…"”

For example in this album, all tracks have .lrc files, but tracks 1, 3, 4 ,6, 7, 10, 11 show some Chinese characters, whereas all the others show the .lrc file.
In the screen capture, Lyric Show 3 (set with %_filename%) shows the lyrics, whereas OpenLyrics shows gibberish.
![Image du presse-papiers (126)](https://github.com/user-attachments/assets/4c05a53a-86c2-442d-b446-ef4812afdc83)

**Comment by apprenti-sorcier** [comment] 2024-11-12 22:11
I might found a culprit. The .lrc files that show fine are encoded as UTF-8 with no BOM. I converted them to Windows 1252 encoding and lo ! OpenLyrics switches to Chinese gibberish.
I converted the tracks that didn’t show fine to UTF-8 (BOM of no BOM) and now they are shown all right in OpenLyrics.
So now the problem seems clarified, waiting for a correction please.
Thanks in advance.

**Comment by jacquesh** [comment] 2024-11-13 20:39
Ah ok great, thanks. That's....very strange. Just to clarify, you've set "Storage Directory" to "Same directory as the track" and then: 
* With the contents of the lyrics file encoded in UTF-8 it always works correctly
* With the contents of the lyrics file encoded in Windows 1252, it works correctly when the "Local files" filename format is `%filename%`, but decodes incorrectly when the filename format is `$replace([%artist% - ][%title%],/,-,\,-,<,-,>,-,:,-,",-,|,-,?,-,*,-)`

Is that accurate? That's very weird, the name of the file really shouldn't impact the decoding at all (I was going to say it looked like another instance of #364). Could you possibly upload the exact Windows 1252-encoded file, along with the exact name you have the file saved under?

**Comment by jacquesh** [comment] 2024-11-16 10:18
Ah ok, yeah that makes more sense. Thanks for the extra testing and clarification! In that case I'm going to say this is another instance/duplicate of #364.

If you could upload the exact file causing your issue there, then that would help with additional examples to test against :)

**Closed by jacquesh** 2024-11-16 10:18 UTC
