### ISSUE TITLE
Support for alpha channel in the lyrics panel background color.

### ISSUE THREAD

**Issue by ac-saro** [jacquesh/foo_openlyrics#282] opened 2023-07-16 13:07 UTC
I would appreciate it if there was a semi-transparent or transparent feature for the background wallpaper.
I would appreciate it if there was always-on-top functionality that doesn't get obscured by other windows.

**Comment by jacquesh** [comment] 2023-07-17 17:35
Duplicate of #41

**Closed by jacquesh** 2023-07-17 17:35 UTC
