### ISSUE TITLE
Autosave doesn't respect Never option

### ISSUE THREAD

**Issue by Azuriye** [jacquesh/foo_openlyrics#327] opened 2024-01-21 21:13 UTC
I have disabled the Autosave feature (set it Never) but when searching for the lyrics manually and hitting the OK or Apply option the lyric file gets saved locally instead of just displaying them on the foobar2k lyric panel.

#### Steps to reproduce
1. Search for lyrics (manually)
2. Highlight any search
3. Click the OK or Apply button
4. Check the File Explorer to confirm the lyric file is saved.

#### Expected behavior
It shouldn't save the file without the user manually right-clicking the lyric and using the Save Lyrics option. But instead when hitting Apply or OK (not sure which button will be more meaningful in this context) it should only display the lyrics on the lyric panel.

#### Versions
* foobar2000 version: foobar2000 version: 2.1
* OpenLyrics version: OpenLyrics version: 1.8

#### Debug logs
[console.txt](https://github.com/jacquesh/foo_openlyrics/files/14002842/console.txt)
(I've clicked the Apply button and OK button as well hence you can see there's two save files)

**Comment by Azuriye** [comment] 2024-01-21 21:40
Okay I've just searched up and there seems to be a similar issue as well reported 2 years ago.

Just to make things clear, in the old lyric plugin hitting Apply or OK (Not sure which button it was) only displays the lyrics on the panel which was helpful for me to quickly identify if the lyrics match to the song or not. 

Instead of entirely relying on the Lyric preview panel when searching manually it'd be better for the user to click either OK or Apply, or maybe change the functionality of maybe the Apply button? So that the user can Apply multiple lyrics from the manual search to see which lyric he/she is satisfied with.

**Comment by jacquesh** [comment] 2024-01-22 08:35
Duplicate of #89

**Closed by jacquesh** 2024-01-22 08:35 UTC
