### ISSUE TITLE
Auto-detect "non-lyric" lyrics

### ISSUE THREAD

**Issue by Quaraxkad** [jacquesh/foo_openlyrics#414] opened 2024-10-13 19:07 UTC
Would it be possible to automatically detect and ignore lyric results that are returned that don't actually include any lyrics? NetEase in particular *very* often returns results with two [00:00.00] timestamped lines that only show song credits and not any actual lyrics. For example, if you search for "No Time for Prayer" by "Jenner" you get two results from NetEase, both of which are only credits.

```
[00:00.00] 作词 : Aleksandra Stamenković
[00:00.00] 作曲 : Aleksandra Stamenković
```
```
[00:00.00] 作词 : Anja Mirković/Aleksandra Stamenković
[00:00.00] 作曲 : Aleksandra Stamenković
```

**Comment by jacquesh** [comment] 2024-10-13 19:10
You've not technically asked for lyrics with a single line (on the contrary) but since it's the same in spirit, I'm going to say this is a duplicate of #409

**Closed by jacquesh** 2024-10-13 19:10 UTC
