### ISSUE TITLE
Some songs show this error even if I have a local file saved: Auto-search skipped because it failed too many times. Manually request a lyrics search to try again.

### ISSUE THREAD

**Issue by DitherMan420** [jacquesh/foo_openlyrics#288] opened 2023-07-23 13:57 UTC
I believe this issue has come up in the past and was fixed? I think it is back. Any ideas?

**Comment by DitherMan420** [comment] 2023-07-23 16:09
Sorry I think this was an error on my part. I thought I had local lyrics but it looks like the lyric file naming wasn't an exact match so it wasn't seeing it. A manual search fixed it and now it plays properly.

**Comment by jacquesh** [comment] 2023-07-24 18:57
Sounds like the issue is resolved so I'm closing this. Note that openlyrics will stop searching (and show that message) if lyrics are not found in normal searches for long enough. Manually searching will refresh this, but it means that if search fails for a while because lyrics are not available online, and then you manually download & save lyrics (or do so by some mechanism other than openlyrics), it will continue to show that message until you explicitly request a search for lyrics.

**Closed by jacquesh** 2023-07-24 18:57 UTC

**Comment by DitherMan420** [comment] 2023-07-24 20:35
> Sounds like the issue is resolved so I'm closing this. Note that openlyrics will stop searching (and show that message) if lyrics are not found in normal searches for long enough. Manually searching will refresh this, but it means that if search fails for a while because lyrics are not available online, and then you manually download & save lyrics (or do so by some mechanism other than openlyrics), it will continue to show that message until you explicitly request a search for lyrics.

Thanks. I just have one question though. Why is it that the majority of instrumental songs seem to pull in chinese, or nonsense?

**Comment by jacquesh** [comment] 2023-07-24 20:38
NetEase and/or QQMusic (which are both chinese providers) tend to give you lyrics (in chinese) for instrumental tracks (often just translating to "no lyrics" or something like that).

**Comment by DitherMan420** [comment] 2023-07-24 20:48
> NetEase and/or QQMusic (which are both chinese providers) tend to give you lyrics (in chinese) for instrumental tracks (often just translating to "no lyrics" or something like that).

Thank you! That makes perfect sense. I have been confused about that for years, ha.
